# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CommonTools' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CommonTools

  target 'CommonToolsTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'CommonToolsUITests' do
    # Pods for testing
  end

end
